# Read the data

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame({
    "Color": ["Red", "Green", "Blue", "Green", "Red"],
    "Size": ["Small", "Medium", "Large", "Medium", "Small"],
    "City": ["Hyderabad", "Delhi", "Mumbai", "Delhi", "Chennai"],
    "Target": [10, 20, 15, 25, 12]
})

df

   Color    Size       City  Target
0    Red   Small  Hyderabad      10
1  Green  Medium      Delhi      20
2   Blue   Large     Mumbai      15
3  Green  Medium      Delhi      25
4    Red   Small    Chennai      12

# Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
df["Color_Label"] = LabelEncoder().fit_transform(df["Color"])

df[["Color", "Color_Label"]]

   Color  Color_Label
0    Red            2
1  Green            1
2   Blue            0
3  Green            1
4    Red            2

# One-Hot Encoding

In [5]:
one_hot = pd.get_dummies(df["Color"], prefix="Color")
one_hot

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1       False         True      False
2        True        False      False
3       False         True      False
4       False        False       True

In [6]:
ohe = pd.get_dummies(df, columns=["Color"])
print(ohe)

     Size       City  Target  Color_Label  Color_Blue  Color_Green  Color_Red
0   Small  Hyderabad      10            2       False        False       True
1  Medium      Delhi      20            1       False         True      False
2   Large     Mumbai      15            0        True        False      False
3  Medium      Delhi      25            1       False         True      False
4   Small    Chennai      12            2       False        False       True

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[["City"]])   
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out(["City"]))

In [15]:
encoded_df

   City_Chennai  City_Delhi  City_Hyderabad  City_Mumbai
0           0.0         0.0             1.0          0.0
1           0.0         1.0             0.0          0.0
2           0.0         0.0             0.0          1.0
3           0.0         1.0             0.0          0.0
4           1.0         0.0             0.0          0.0

# Ordinal Encoding

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
order = [["Small", "Medium", "Large"]]
df["Size_Ordinal"] = OrdinalEncoder(categories=order).fit_transform(df[["Size"]])
df[["Size", "Size_Ordinal"]]

     Size  Size_Ordinal
0   Small           0.0
1  Medium           1.0
2   Large           2.0
3  Medium           1.0
4   Small           0.0

# Target Encoding

In [9]:
te = df.groupby("City")["Target"].mean()

df["City_Target_Enc"] = df["City"].map(te)
df[["City", "City_Target_Enc"]]

        City  City_Target_Enc
0  Hyderabad             10.0
1      Delhi             22.5
2     Mumbai             15.0
3      Delhi             22.5
4    Chennai             12.0

# Frequency Encoding

In [10]:
freq = df["City"].value_counts()

df["City_Freq_Enc"] = df["City"].map(freq)
df[["City", "City_Freq_Enc"]]

        City  City_Freq_Enc
0  Hyderabad              1
1      Delhi              2
2     Mumbai              1
3      Delhi              2
4    Chennai              1

# Binary Encoding

In [11]:
import category_encoders as ce

In [12]:
data_binary = ce.BinaryEncoder(cols=["City"]).fit_transform(df["City"])

In [13]:
data_binary

   City_0  City_1  City_2
0       0       0       1
1       0       1       0
2       0       1       1
3       0       1       0
4       1       0       0

# Feature Hashing

In [21]:
from sklearn.feature_extraction import FeatureHasher

In [24]:
fh = FeatureHasher(n_features=4, input_type="string")
hashed = fh.transform([[city] for city in df["City"]])
hashed_df = pd.DataFrame(hashed.toarray())
hashed_df

     0    1    2    3
0 -1.0  0.0  0.0  0.0
1  0.0  0.0  0.0 -1.0
2  0.0  0.0 -1.0  0.0
3  0.0  0.0  0.0 -1.0
4  0.0  0.0  1.0  0.0

In [4]:
df

   Color    Size       City  Target
0    Red   Small  Hyderabad      10
1  Green  Medium      Delhi      20
2   Blue   Large     Mumbai      15
3  Green  Medium      Delhi      25
4    Red   Small    Chennai      12